"""Constants to be used in the game"""

APP_WIDTH = 1200
APP_HEIGHT = 600
CANVAS_HEIGHT = 500
CANVAS_WIDTH = 500

MIN_CELL_SIZE = 5
MAX_CELL_SIZE = 100
ACCEPTED_CELL_SIZES = [
    x for x in range(10, 100)
    if CANVAS_HEIGHT % x == 0]
CELL_SIZE = ACCEPTED_CELL_SIZES[len(ACCEPTED_CELL_SIZES) // 2]
